use super::error::LocationError;
use super::state::SimulationState;
use super::time::Timestamp;
use crate::geographic::Coordinate;

/// What produced a sample.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LocationSource {
    /// Generated by a movement model.
    Simulation,
    /// Interpolated from a recorded route.
    Replay,
    /// Injected by a test provider.
    Test,
}

/// The canonical sample emitted by the simulation core.
///
/// Unknown speed/course are `None` here; mapping to platform sentinels
/// (Core Location's `-1`) is the platform adapter's job.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SyntheticLocation {
    pub timestamp: Timestamp,
    pub coordinate: Coordinate,
    pub altitude_m: f64,
    pub horizontal_accuracy_m: f64,
    pub vertical_accuracy_m: f64,
    /// Ground speed in m/s.
    pub speed_mps: Option<f64>,
    /// Direction of travel in degrees clockwise from true north, `[0, 360)`.
    pub course_deg: Option<f64>,
    pub source: LocationSource,
    pub simulation_state: SimulationState,
}

impl SyntheticLocation {
    /// Checks every field is individually emit-safe. Cross-sample checks
    /// (movement limits, timestamp monotonicity) belong to the validation pipeline.
    pub fn validate(&self) -> Result<(), LocationError> {
        if !self.altitude_m.is_finite() {
            return Err(LocationError::NonFinite("altitude"));
        }
        for (name, v) in [
            ("horizontal accuracy", self.horizontal_accuracy_m),
            ("vertical accuracy", self.vertical_accuracy_m),
        ] {
            if !v.is_finite() {
                return Err(LocationError::NonFinite(name));
            }
            if v < 0.0 {
                return Err(LocationError::NegativeAccuracy(name));
            }
        }
        if let Some(speed) = self.speed_mps {
            if !speed.is_finite() {
                return Err(LocationError::NonFinite("speed"));
            }
            if speed < 0.0 {
                return Err(LocationError::NegativeSpeed(speed));
            }
        }
        if let Some(course) = self.course_deg {
            if !course.is_finite() {
                return Err(LocationError::NonFinite("course"));
            }
            if !(0.0..360.0).contains(&course) {
                return Err(LocationError::CourseOutOfRange(course));
            }
            if !matches!(self.speed_mps, Some(s) if s > 0.0) {
                return Err(LocationError::CourseWithoutMotion);
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> SyntheticLocation {
        SyntheticLocation {
            timestamp: Timestamp::from_nanos(0),
            coordinate: Coordinate::new(12.9352, 77.6245).unwrap(),
            altitude_m: 920.0,
            horizontal_accuracy_m: 5.0,
            vertical_accuracy_m: 8.0,
            speed_mps: Some(1.4),
            course_deg: Some(90.0),
            source: LocationSource::Simulation,
            simulation_state: SimulationState::Running,
        }
    }

    #[test]
    fn valid_samples_pass() {
        assert_eq!(sample().validate(), Ok(()));
        let stationary = SyntheticLocation {
            speed_mps: Some(0.0),
            course_deg: None,
            ..sample()
        };
        assert_eq!(stationary.validate(), Ok(()));
        let unknown = SyntheticLocation {
            speed_mps: None,
            course_deg: None,
            ..sample()
        };
        assert_eq!(unknown.validate(), Ok(()));
    }

    #[test]
    fn rejects_bad_fields() {
        let s = sample();
        let cases = [
            (
                SyntheticLocation {
                    altitude_m: f64::NAN,
                    ..s
                },
                LocationError::NonFinite("altitude"),
            ),
            (
                SyntheticLocation {
                    horizontal_accuracy_m: f64::INFINITY,
                    ..s
                },
                LocationError::NonFinite("horizontal accuracy"),
            ),
            (
                SyntheticLocation {
                    vertical_accuracy_m: -1.0,
                    ..s
                },
                LocationError::NegativeAccuracy("vertical accuracy"),
            ),
            (
                SyntheticLocation {
                    speed_mps: Some(-0.1),
                    ..s
                },
                LocationError::NegativeSpeed(-0.1),
            ),
            (
                SyntheticLocation {
                    speed_mps: Some(f64::NAN),
                    ..s
                },
                LocationError::NonFinite("speed"),
            ),
            (
                SyntheticLocation {
                    course_deg: Some(360.0),
                    ..s
                },
                LocationError::CourseOutOfRange(360.0),
            ),
            (
                SyntheticLocation {
                    course_deg: Some(-1.0),
                    ..s
                },
                LocationError::CourseOutOfRange(-1.0),
            ),
            (
                SyntheticLocation {
                    speed_mps: Some(0.0),
                    ..s
                },
                LocationError::CourseWithoutMotion,
            ),
            (
                SyntheticLocation {
                    speed_mps: None,
                    ..s
                },
                LocationError::CourseWithoutMotion,
            ),
        ];
        for (loc, expected) in cases {
            assert_eq!(loc.validate(), Err(expected));
        }
    }
}
